export const mainTheme = {
  // token: { fontFamily: "adineuePRO, __adineuePRO_Fallback" },
  components: {
    Menu: {
      fontSize: 16,
      iconSize: 24,
      itemActiveBg: "#ad2b0899",
      itemActiveColor: "#262621",
      itemHoverColor: "#262621",
      itemColor: "#262621",
      itemSelectedBg: "#ad2b08",
      itemSelectedColor: "#ffffff",
      iconColor: "#262621",
      subMenuItemBg: "#ffffff11",
    },
    Form: {
      colorError: "#E53935",
    },
    Checkbox: {
      colorPrimary: "#ad2b08",
      colorPrimaryHover: "#ad2b08",
    },
    Select: {
      // colorTextQuaternary: "#ffffff",
      colorBgContainer: "rgba(0,0,0,0)",
      fontSize: 18,
      optionSelectedColor: "#ffffff",
      optionSelectedBg: "#ad2b08",
      optionActiveBg: "#ad2b0855",
      optionActiveColor: "#efefef",
      colorBorder: "#efefef",
      colorBgElevated: "#efefef",
      selectorBg: "#efefef",
      colorText: "#262621",
      colorTextPlaceholder: "#5d5d5d",
      // activeOutlineColor: "#5d5d5d",
      // activeBorderColor: "#5d5d5d",
      hoverBorderColor: "#5d5d5d",
    },
    TimePicker: {
      colorTextQuaternary: "#ad2b08",
      fontSize: 16,
      colorTextPlaceholder: "#262621",
      colorBgElevated: "#efefef",
      colorText: "#262621",
      colorTextHeading: "#262621",
      colorTextDisabled: "#26262155",
      colorIcon: "#ad2b08",
      colorIconHover: "#ad2b08",
      colorPrimary: "#ad2b08",
    },
    DatePicker: {
      colorTextQuaternary: "#ad2b08",

      fontSize: 16,
      colorTextPlaceholder: "#262621",
      colorBgElevated: "#efefef",
      colorText: "#262621",
      colorTextHeading: "#262621",
      colorTextDisabled: "#26262155",
      colorIcon: "#ad2b08",
      colorIconHover: "#ad2b08",
      colorPrimary: "#ad2b08",
    },
    Upload: {
      colorFillAlter: "rgba(0,0,0,0)",
      colorBorder: "#5d5d5d",
      colorBorderHover: "#5d5d5d",
      colorText: "#5d5d5d",
    },
    Table: {
      headerBg: "#E6E9EA",
      colorBgContainer: "#FDFDFD",
      colorText: "#262621",
      borderColor: "#DFE1E3",
      headerColor: "#262621",
      fontSize: 18,
      footerColor: "#FDFDFD",
      // marginXXS: 4,
      colorLinkActive: "#FDFDFD",
      headerSplitColor: "#262621",
    },
    Pagination: {
      itemActiveBg: "#ad2b08",
      colorPrimary: "#F3F3F3",
      colorPrimaryHover: "#F3F3F3",
    },
    Input: {
      colorTextPlaceholder: "#5d5d5d ",
      colorIcon: "#5d5d5d",
    },
    Radio: {
      colorPrimary: "#ad2b08",
    },
  },
};
